### ISSUE TITLE
Why was vis-commentary.lua renamed to init.lua?

### ISSUE THREAD

**Issue by ImagineInfinity** [lutobler/vis-commentary#9]
Plugin does not work unless init.lua is renamed vis-commentary.lua

**Comment by lutobler** [comment]
See https://github.com/lutobler/vis-commentary/pull/8, I made this originally a while before standards formed on how plugins should be structured.

**Comment by ingolemo** [comment]
Ironically, the main reason I suggested this change is so that I wouldn't have to manually move the file around any more. You just go to your plug-ins directory, clone the whole repo (so that the code ends up at `~/.config/vis/plugins/vis-commentary/init.lua`), and vis will find it just fine.

When you `require("somthing")` vis will check various places for a `something.lua` file but it will also check for a `something/init.lua` file too. See martanne/vis#800
